name: 'CI: Code Quality Checks'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm run lint

      - name: Check for Vulnerabilities
        run: pnpm audit --prod

      - name: Build Project
        run: pnpm run build 