name: 'Content Validation'

on:
  push:
    paths:
      - 'docs/**'
      - 'src/**'
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  validate-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Content
        run: pnpm run build:content

      - name: Check for Broken Links
        run: |
          # Install markdown-link-check if not available
          npm install -g markdown-link-check
          
          # Check only external links in MDX files (skip internal /docs/ links)
          find docs -name "*.mdx" -exec sh -c '
            echo "Checking external links in $1..."
            markdown-link-check "$1" --config .markdown-link-check.json 2>/dev/null || true
          ' _ {} \;

      - name: Validate MDX Syntax
        run: |
          # Check if all MDX files can be parsed by contentlayer
          pnpm run build:content
          
          # If we get here, all MDX files are valid
          echo "✅ All MDX files are valid"

      - name: Check Image References
        run: |
          # Check if all referenced images exist
          find docs -name "*.mdx" -exec grep -o '/res/[^"'\''\s]*\.[a-zA-Z0-9]\+' {} \; | sort | uniq | while read -r img; do
            if [ ! -f "public$img" ]; then
              echo "❌ Missing image: $img"
              exit 1
            fi
          done 